### ISSUE TITLE
Bug when scrolling docs

### ISSUE THREAD

**Issue by Puckost** [knuckleswtf/scribe#395]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
I created docs using 'type': 'laravel' and everything works. But when i look at api docs there is some problem with scrolling and toc.
When i scroll down, it is less bugy, but when i scroll up it is impossible to scroll. It always returns me to same section.
I tried the old minimized js version of theme-default-3.19.1.js and it works (some minor issue was duplicated table of content, but it worked).

I am using Pop!_OS 21.10 with Firefox 95.0
It seems to work fine in Chrome Version 96.0.4664.110 (Official Build) snap (64-bit)

Any idea how to fix it?

**My environment:**
 - PHP version (from `php -v`): 8.1.0
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 8.76.1
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.19.1

**Comment by bjhijmans** [comment]
I had the same problem, and in my case it seemed to be related to a js crash in the middle of the script with the exception "uncaught type error: hljs.highlightAll is not a function" If you get that error as well, it's related to #393

**Comment by Puckost** [comment]
I dont get any errors in console. The code in js looks fine and as i said everything works fine in Chrome, problem appears only in FF.
I think the problem is in `IntersectionObserver` and its parameters, but i did not figure out yet how to solve it.

**Comment by shalvah** [comment]
I think what you're pointing out is [this](https://github.com/knuckleswtf/scribe/issues/374#issuecomment-984614502). If we don't find a fix, we might revert all of that.

**Comment by shalvah** [comment]
Should be fixed in 3.20 (in a few hours).
